services:
  jupyter:
    build: .
    environment:
      CUDA_VISIBLE_DEVICES: "-1"
    ports:
      - "8888:8888"
    volumes:
      # This syncs the local folder (.) to the /app folder inside the container
      - .:/app
